### ISSUE TITLE
文件夹的标题行显示可以优化

### ISSUE THREAD

**Issue by Yorks0n** [tw93/Maple#10]
今天刚发现的插件，支持关键词搜索非常爽，但感觉文件夹的标题行显示可以优化一下，如果有多级文件夹
![Snipaste_2023-08-07_16-47-32](https://github.com/tw93/Maple/assets/24605974/add7e362-a958-40f6-a4d8-8c5aa43fe875)
现在显示是这样的：
![Snipaste_2023-08-07_16-48-07](https://github.com/tw93/Maple/assets/24605974/7a3c82b6-14f6-43d7-ac6a-a230ad2f456b)
增加个点击展开/收起，或者改一下显示布局感觉都会更好看，比如如下这样（仅作为建议）：
![Snipaste_2023-08-07_16-56-25](https://github.com/tw93/Maple/assets/24605974/cced1a5b-4736-4190-a76a-cf3db89ab394)

**Comment by tw93** [comment]
<img width="312" alt="image" src="https://github.com/tw93/Maple/assets/8736212/a95ab704-1781-41a2-86ad-7c35e4269eef">
这几个是由于被你收起来了导致的吗？还是本地这个下面没有内容？

**Comment by Yorks0n** [comment]
不是，实际这几个文件夹是嵌套的，大概是 其他书签-Bioinfomatics-Biotool-DataVis，就显示成这样了。

**Comment by tw93** [comment]
哦哦 懂你意思了 其实这里有没有办法整理一波书签，然后再来使用maple，效果会好不少，此外为什么你的书签在 其他书签里面哦？

**Comment by Yorks0n** [comment]
确实整理一下是最好的，不过这已经是我整理完的结果，所以套了好几层文件夹。至于其他书签，我好像一直是书签栏+其他书签的配置，书签栏显示在顶部一排，其他书签在最右边显示成一个文件夹。

**Comment by tw93** [comment]
好的 我想办法优化一下

**Comment by 2019YKL** [comment]
支持 @Yorks0n 比如我有一个文件夹是这样分类的：图片处理/去除背景；图片处理/智能去除。

但图片处理作为父级文件夹确实不需要有任何书签。

![image](https://github.com/tw93/Maple/assets/51532948/3f826b7c-bf49-445d-bc98-58833a303365)

感谢作者开发这款插件，我找这类插件好久了！😚

**Comment by tw93** [comment]
哈哈哈 谢谢喜欢，那就安排～

**Comment by Tohrusky** [comment]
@tw93 不小心直接提交主分支了，可以开下branch保护吗（
先搞成这样可以吗，比较省事
![2975bb4eba9ae93852f6500cd86eb826](https://github.com/tw93/Maple/assets/65994850/2fe4df8d-4a2c-4df6-9c87-befb4c98aa3a)

**Comment by tw93** [comment]
@Tohrusky 已经开启，谢谢提醒
上面截图有一个小优化点，假如是第二级的书签文件夹（书签栏的下一级的）就不要出现 书签栏>xxx 了，这样会显得更加简洁舒服，假如是第三级的时候，才显示类似于 Local>test ,但是这里假如Local>test 下面全部是文件夹的形式，那么就不要展示 Local>test ，而是直接 Local >test > tttttt 这样更好
此外这里结合，假如 Local>test 后面有item，前面都是 文件夹的话，那就将item给前置，这样就会更好看了。

**Comment by tw93** [comment]
@1761178412 安排中

**Comment by tw93** [comment]
已经优化，可以去release下面下载最新的本地包验证，官方包审批中
