### ISSUE TITLE
没有分类的书签样式问题.

### ISSUE THREAD

**Issue by inixue** [tw93/Maple#2]
![WechatIMG90](https://github.com/tw93/Maple/assets/23271866/c3c353aa-4d05-4525-a2ac-a98cd4753210)

**Comment by tw93** [comment]
试试把文件夹都放后面

**Comment by tw93** [comment]
不过样式有问题 明天发一个版本

**Comment by tw93** [comment]
已经修复，不过需要等chrome 审核通过，着急可以试试本地版本，可以去 readme 里面找找
