### ISSUE TITLE
The Maple.zip Link  in README Return Page not found

### ISSUE THREAD

**Issue by yikZero** [tw93/Maple#31]
> 假如你不可访问，可以下载 [Maple.zip](https://github.com/tw93/Maple/raw/main/resource/Maple.zip)，解压以后，参考 [Loading an unpacked extension](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked) 来使用本地包。

This **Maple.zip** link is not available: https://github.com/tw93/Maple/raw/main/resource/Maple.zip

**Comment by jeasonnow** [comment]
Thx for raising the issue, which will be fixed in this [Pull Request](https://github.com/tw93/Maple/pull/32)
