### ISSUE TITLE
【feature】能否支持一键展开/收起文件夹

### ISSUE THREAD

**Issue by UrielHui** [tw93/Maple#38]
能否支持一键展开/收起 所有文件夹？
我在书签栏根目录放了较多书签和文件夹，然后在拓展里根目录书签翻完才能看到文件夹，往下滑是一个文件夹书签翻完，才能到下一个文件夹，比较不好定位。一键收起文件夹之后我能够点击到我想要找的文件夹

**Comment by tw93** [comment]
🤣 其实是支持的，你试试点击书签上面的文件夹名称，甚至可以记住你的选择
