### ISSUE TITLE
feat: 能否支持书签的增删

### ISSUE THREAD

**Issue by zwmmm** [tw93/Maple#39]
目前我在使用arc浏览器，不喜欢他的pin功能（每次打开书签，合上就找不到了），使用这个插件正好可以弥补arc没有书签UI的能力，但是缺少收藏和删除的快捷操作

ps: 如果愿意接受这个功能，我可以进行功能的开发，目前想的就是在每一个列的最后加一个添加的按钮，表示将当前的书签添加到这个目录

**Comment by tw93** [comment]
抱歉 这个功能我认为会让代码变得更加复杂，同时很多时候删除书签，普通浏览器的书签管理可以很好删除，但是arc，我擦，就不好搞了，一般可以导出导入或者去原来书签的里面删除
