### ISSUE TITLE
新特性支持

### ISSUE THREAD

**Issue by CharleeWa** [tw93/Maple#4]
嗨 @tw93，你好！

谢谢你做的这个项目，非常棒❤，我昨天也把它集成到我的Chrome上了，界面突然变得干净舒服。不过，我在用的过程中，发现有两点不便，看看是否考虑。

1. 一个是当你的收藏书签过多时，你需要通过下滑滚动条查找，我觉得加一个类似于搜索应该会提升索引效率；
2. 还有一个常用的场景是，当你想打开某个 tag 下的所有书签时需要一个个点击打开。

**Comment by tw93** [comment]
谢谢喜欢 下一个版本我大概知道怎么做了🌚

**Comment by tw93** [comment]
哈哈 两个都支持了，这样，你可以先本地下载这个 https://github.com/tw93/Maple/raw/main/resource/Maple.zip
然后等我这边1.2 谷歌审核通过，可以先玩玩看

**Comment by CharleeWa** [comment]
太效率了 ❤
