### ISSUE TITLE
Windows下快捷键与Chrome快捷键冲突

### ISSUE THREAD

**Issue by preflower** [tw93/Maple#5]
## 问题
Windows操作系统下的`Ctrl + E`快捷键与Chrome快捷键冲突

## 参考
- [Chrome keyboard shortcuts](https://support.google.com/chrome/answer/157179#zippy=%2Caddress-bar-shortcuts)

**Comment by tw93** [comment]
我去看看 谢谢提醒

**Comment by preflower** [comment]
> 我去看看 谢谢提醒 不过 command+b 现在在文本里面是粗体的快捷键，你这边ctrl+b有没有其他的冲突

如果考虑 Editor 快捷键的话那场景就复杂了; 目前`Ctrl/⌘ + b`在网页浏览时打开没有其他冲突

**Comment by tw93** [comment]
谢谢提醒，已经修改。辛苦等chrome 1.2 版本的审核，当前请辛苦自己去扩展快捷键配置改就好了
<img width="855" alt="image" src="https://github.com/tw93/Maple/assets/8736212/14346c86-ce6f-4961-9932-3bb44f5d268c">
