### ISSUE TITLE
[BUG] 不能正常新建标签页

### ISSUE THREAD

**Issue by Tohrusky** [tw93/Maple#7]
### Describe the bug
不能正常新建标签页，会显示一个空白的页面

### To reproduce
安装插件后，点击“New Tab”

### Context
- OS: MaoOS Ventura 13.5
- Arch: arm64
- Chrome Version: 115.0.5790.114 (Official Build) (arm64)

### Additional context
![2827f2140c375b3aebabb4895edc1e93](https://github.com/tw93/Maple/assets/65994850/a25139e3-31b6-4b7d-80a4-5b211d6b07f7)

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title id="title"></title>
    <style>
      html body {
        margin: 0;
        padding: 0;
        background-repeat: no-repeat;
        background-size: 100% 100%;
        background-attachment: fixed;
      }
    </style>
  </head>
  <body>
    <script src="newtab.js"></script>
  </body>
</html>
```

**Comment by tw93** [comment]
这个其实是一个特性，替换了原来的默认标签页面，你试试 command + e
替换原来标签页这个我想着看能否放一个配置出来

**Comment by Tohrusky** [comment]
感谢！使用是正常的，command e 可以正常拉起。我记得最开始的版本似乎不会替换？还以为这是bug呢😂

**Comment by Tohrusky** [comment]
我比较偏向保留，因为个人经常开关chrome，标签页默认的随机背景挺好看的🤡
用目前方案的话，或许可以用bing 图片api 来代替纯色背景？

**Comment by tw93** [comment]
https://github.com/tw93/Maple/raw/main/resource/Maple.zip
试试这个本地包，这样是不是ok

**Comment by Tohrusky** [comment]
其实我大概想要这种效果 https://github.com/Tohrusky/Maple/commit/f7c3e396f6878e23166762076a694e25c17f286b
没接触过原生，先糊写了一下，缓存没弄（
P. S. 原来代码这种特殊缩进是有啥讲究吗

**Comment by tw93** [comment]
哈哈哈 你安装规则来就好
实现小功能我更喜欢用原生js 简单高效一把梭

**Comment by Tohrusky** [comment]
好的，我等会试着完善一下🤣

**Comment by tw93** [comment]
赞，看到了，代码已经合并，放下一个版本发布，到时候可以看看还有啥需要优化的，我给你来加直接开发权限

**Comment by Tohrusky** [comment]
同意了，感谢邀请

~~第一反应是把 eslint 和 action release 配一下（让git追踪一个zip文件还是不太优雅~~


话说浏览器扩展/油猴开发用框架的多吗？可能兼容性会好一点？
类似这种 https://github.com/PlasmoHQ/plasmo

**Comment by tw93** [comment]
都可以玩的，我只不过懒，就直接从新建文件开始写了，你有兴趣可以直接改着看看
可以一起交流前端，我本职工作就是做前端的，可以帮你简单review code，哈哈
